// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrgwehhtfumqmoqasrnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yZ3dlaGh0ZnVtcW1vcWFzcm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODA0NzIsImV4cCI6MjA2ODM1NjQ3Mn0.m-TwYtmOyarKFVg99qiNv4vHvKVfoysaIN0NzvNcm6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});